-- =============================================================================
-- CASEPILOT — Module 1: Foundation
-- Script: 05_roles_and_grants.sql
-- Purpose: Create roles and grant appropriate permissions
-- Author: CasePilot Team
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- ROLES
-- =============================================================================

-- CASEPILOT_ADMIN: Full access to all schemas and objects
CREATE ROLE IF NOT EXISTS CASEPILOT_ADMIN
    COMMENT = 'CasePilot administrator - full access to all objects';

-- CASEPILOT_ANALYST: Read/write access to investigation and analytics
CREATE ROLE IF NOT EXISTS CASEPILOT_ANALYST
    COMMENT = 'CasePilot analyst - manages investigations and cases';

-- CASEPILOT_VIEWER: Read-only access for dashboard and reporting
CREATE ROLE IF NOT EXISTS CASEPILOT_VIEWER
    COMMENT = 'CasePilot viewer - read-only dashboard access';

-- =============================================================================
-- ROLE HIERARCHY
-- ACCOUNTADMIN -> CASEPILOT_ADMIN -> CASEPILOT_ANALYST -> CASEPILOT_VIEWER
-- =============================================================================
GRANT ROLE CASEPILOT_VIEWER  TO ROLE CASEPILOT_ANALYST;
GRANT ROLE CASEPILOT_ANALYST TO ROLE CASEPILOT_ADMIN;
GRANT ROLE CASEPILOT_ADMIN   TO ROLE ACCOUNTADMIN;

-- =============================================================================
-- WAREHOUSE GRANTS
-- =============================================================================
GRANT USAGE ON WAREHOUSE CASEPILOT_WH TO ROLE CASEPILOT_ADMIN;
GRANT USAGE ON WAREHOUSE CASEPILOT_WH TO ROLE CASEPILOT_ANALYST;
GRANT USAGE ON WAREHOUSE CASEPILOT_WH TO ROLE CASEPILOT_VIEWER;

-- =============================================================================
-- DATABASE GRANTS
-- =============================================================================
GRANT USAGE ON DATABASE CASEPILOT_DB TO ROLE CASEPILOT_ADMIN;
GRANT USAGE ON DATABASE CASEPILOT_DB TO ROLE CASEPILOT_ANALYST;
GRANT USAGE ON DATABASE CASEPILOT_DB TO ROLE CASEPILOT_VIEWER;

-- =============================================================================
-- SCHEMA GRANTS — CASEPILOT_ADMIN (full access to all schemas)
-- =============================================================================
GRANT ALL PRIVILEGES ON SCHEMA CASEPILOT_DB.RAW            TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CASEPILOT_DB.CORE           TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CASEPILOT_DB.ALERTS         TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CASEPILOT_DB.INVESTIGATION  TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CASEPILOT_DB.ANALYTICS      TO ROLE CASEPILOT_ADMIN;

-- Future grants for admin
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CASEPILOT_DB.RAW            TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CASEPILOT_DB.CORE           TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CASEPILOT_DB.ALERTS         TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CASEPILOT_DB.INVESTIGATION  TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CASEPILOT_DB.ANALYTICS      TO ROLE CASEPILOT_ADMIN;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.RAW            TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.CORE           TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.ALERTS         TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.INVESTIGATION  TO ROLE CASEPILOT_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.ANALYTICS      TO ROLE CASEPILOT_ADMIN;

-- =============================================================================
-- SCHEMA GRANTS — CASEPILOT_ANALYST (read/write on investigation + analytics)
-- =============================================================================
GRANT USAGE ON SCHEMA CASEPILOT_DB.RAW            TO ROLE CASEPILOT_ANALYST;
GRANT USAGE ON SCHEMA CASEPILOT_DB.CORE           TO ROLE CASEPILOT_ANALYST;
GRANT USAGE ON SCHEMA CASEPILOT_DB.ALERTS         TO ROLE CASEPILOT_ANALYST;
GRANT USAGE ON SCHEMA CASEPILOT_DB.INVESTIGATION  TO ROLE CASEPILOT_ANALYST;
GRANT USAGE ON SCHEMA CASEPILOT_DB.ANALYTICS      TO ROLE CASEPILOT_ANALYST;

-- Analyst can read raw data
GRANT SELECT ON ALL TABLES IN SCHEMA CASEPILOT_DB.RAW   TO ROLE CASEPILOT_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA CASEPILOT_DB.CORE  TO ROLE CASEPILOT_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.RAW   TO ROLE CASEPILOT_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.CORE  TO ROLE CASEPILOT_ANALYST;

-- Analyst can read/write alerts and investigation
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CASEPILOT_DB.ALERTS        TO ROLE CASEPILOT_ANALYST;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CASEPILOT_DB.INVESTIGATION TO ROLE CASEPILOT_ANALYST;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CASEPILOT_DB.ANALYTICS     TO ROLE CASEPILOT_ANALYST;

GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.ALERTS        TO ROLE CASEPILOT_ANALYST;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.INVESTIGATION TO ROLE CASEPILOT_ANALYST;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.ANALYTICS     TO ROLE CASEPILOT_ANALYST;

-- =============================================================================
-- SCHEMA GRANTS — CASEPILOT_VIEWER (read-only everywhere)
-- =============================================================================
GRANT USAGE ON SCHEMA CASEPILOT_DB.RAW            TO ROLE CASEPILOT_VIEWER;
GRANT USAGE ON SCHEMA CASEPILOT_DB.CORE           TO ROLE CASEPILOT_VIEWER;
GRANT USAGE ON SCHEMA CASEPILOT_DB.ALERTS         TO ROLE CASEPILOT_VIEWER;
GRANT USAGE ON SCHEMA CASEPILOT_DB.INVESTIGATION  TO ROLE CASEPILOT_VIEWER;
GRANT USAGE ON SCHEMA CASEPILOT_DB.ANALYTICS      TO ROLE CASEPILOT_VIEWER;

GRANT SELECT ON ALL TABLES IN SCHEMA CASEPILOT_DB.RAW            TO ROLE CASEPILOT_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA CASEPILOT_DB.CORE           TO ROLE CASEPILOT_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA CASEPILOT_DB.ALERTS         TO ROLE CASEPILOT_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA CASEPILOT_DB.INVESTIGATION  TO ROLE CASEPILOT_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA CASEPILOT_DB.ANALYTICS      TO ROLE CASEPILOT_VIEWER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.RAW            TO ROLE CASEPILOT_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.CORE           TO ROLE CASEPILOT_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.ALERTS         TO ROLE CASEPILOT_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.INVESTIGATION  TO ROLE CASEPILOT_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CASEPILOT_DB.ANALYTICS      TO ROLE CASEPILOT_VIEWER;

-- =============================================================================
-- GRANT ROLES TO CURRENT USER (for trial account setup)
-- =============================================================================
-- Uncomment and replace <YOUR_USERNAME> with your Snowflake username
-- GRANT ROLE CASEPILOT_ADMIN TO USER <YOUR_USERNAME>;

-- Verify
SHOW ROLES LIKE 'CASEPILOT%';
SHOW GRANTS TO ROLE CASEPILOT_ADMIN;
SHOW GRANTS TO ROLE CASEPILOT_ANALYST;
SHOW GRANTS TO ROLE CASEPILOT_VIEWER;
